sudo: required
services:
    - docker

before_install:
  - docker build -t olita1986/react-test -f ./client/dev.Dockerfile ./client

script:
  # run tests
  - docker run olita1986/react-test npm test -- --coverage

after_success:
  - docker build -t olita1986/multi-client ./client
  - docker build -t olita1986/multi-nginx ./nginx
  - docker build -t olita1986/multi-server ./server
  - docker build -t olita1986/multi-worker ./worker
  # log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push olita1986/multi-client
  - docker push olita1986/multi-nginx
  - docker push olita1986/multi-server
  - docker push olita1986/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucker_name: elasticbeanstalk-us-east-2-384718914185
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY